### ISSUE TITLE
Hello,my eye data is already in degrees of visual angle,what should i do?

### ISSUE THREAD

**Issue by AlfredLTennyson** [tmalsburg/saccades#19]
Hello, i have eye gaze data that is already in degrees of visual angle.
In your algorithm , it takes data in pixels. 
What should i do?
I am attaching the data file below with some plots of gaze trajectory and gaze coordinates and velocity plots to make the dataset undertsandable.
https://raw.githubusercontent.com/AlfredLTennyson/eye_gaze_data_for_1_trial/main/T_Trial1.tsv

**Comment by AlfredLTennyson** [comment]
![image](https://user-images.githubusercontent.com/114279791/195977739-2ad25208-dc17-4606-84ec-65ee9544b6a4.png)

This is the plot of eyeX vs eyeY

**Comment by AlfredLTennyson** [comment]
![image](https://user-images.githubusercontent.com/114279791/195977765-48c1d84c-762a-485d-94b6-7372c75070e0.png)

This is the eye X velocity. Please click on the image to see the x and y labels.

**Comment by AlfredLTennyson** [comment]
![image](https://user-images.githubusercontent.com/114279791/195977797-87ff8446-732b-433b-9218-9d24c1591617.png)

this is the plot of eyeX vs Time

**Comment by AlfredLTennyson** [comment]
I have tried I-VT algorithms,but none is doing right classification.
Can you please shed some light as to how i should implement an algorithm?
Attaching the colab file below,so that you can see what is wrong.
https://github.com/AlfredLTennyson/eye_gaze_data_for_1_trial/blob/main/Untitled8.ipynb

**Comment by AlfredLTennyson** [comment]
I am kind of confused here. Can you please help me out with some tips?

**Comment by AlfredLTennyson** [comment]
I do know that your algorithm is R based.

**Comment by tmalsburg** [comment]
Hi there.  Unfortunately, I don't have the time to help you process your data.  But here are a two things that I would try. 1. I would try to run my software on the degree data to see what happens.  The algorithm is in principle invariant to the unit of space and the distortion due to the spherical coordinates is likely too small to matter. 2. A cleaner solution would be to convert the degree coordinates to pixel coordinates using the [gnomonic projection](https://en.wikipedia.org/wiki/Gnomonic_projection). You can likely find code for that in the usual places. From your plots it seems that you're using Python.  I think there is an implementation of the gnomonic projection in the package matplotlib. Hope this helps.
